-- MySQL Script generated by MySQL Workbench
-- Sat Dec  9 07:07:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_table`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_table` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `is_registered` BIT(1) NOT NULL,
  `login` VARCHAR(255) NULL DEFAULT NULL,
  `mail` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `patronymic` VARCHAR(255) NULL DEFAULT NULL,
  `phone_number` VARCHAR(255) NULL DEFAULT NULL,
  `surname` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`type` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `amount_of_people` INT NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL,
  `room_amount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`booking` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date_of` DATE NOT NULL,
  `date_on` DATE NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `type_id` BIGINT NOT NULL,
  `user_id` BIGINT NOT NULL,
  `guest_amount` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKnshfjkekcgpwaykdfeqwpn4r4` (`type_id` ASC) VISIBLE,
  INDEX `FK3bdpxgttcpc834g9tb7ex0066` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK3bdpxgttcpc834g9tb7ex0066`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user_table` (`id`),
  CONSTRAINT `FKnshfjkekcgpwaykdfeqwpn4r4`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`image` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type_id` BIGINT NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKdu6nlgy4njp7fsk8ugaafau3u` (`type_id` ASC) VISIBLE,
  CONSTRAINT `FKdu6nlgy4njp7fsk8ugaafau3u`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`type` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`number`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`number` (
  `n` INT NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_role` (
  `user_id` BIGINT NOT NULL,
  `roles` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FK5cwpllhe458f6j6fb7rmhfyt2` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK5cwpllhe458f6j6fb7rmhfyt2`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user_table` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `mydb`.`number`
-- -----------------------------------------------------

Create TABLE IF NOT EXISTS 'mydb'.'number' (
    'n' int not null)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

-- Data insertion
INSERT INTO `number` (`n`) VALUES
                                     (1),
                                     (2),
                                     (3),
                                     (4),
                                     (5),
                                     (6),
                                     (7),
                                     (8),
                                     (9),
                                     (10);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
